# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Runs MC simulation
#'
#' @param Expiry Time to maturity
#' @param Strike strike price
#' @param Spot price of the underlying at the moment of option pricing
#' @param Vol annualized volatility rate
#' @param r annualized risk-free rate
#' @param barrier barrier level
#' @param NumberOfPaths number of simulations
#' @return option price
getCallPrice <- function(Expiry = 0.5, Strike = 100, Spot = 120, Vol = 0.2, r = 0.06, barrier = 50, NumberOfPaths = 10000L) {
    .Call(`_monteCarlo306068_getCallPrice`, Expiry, Strike, Spot, Vol, r, barrier, NumberOfPaths)
}

